"""add booking type and lessons table

Revision ID: 22dac19b8b8a
Revises: 
Create Date: 2026-05-20 15:17:27.017028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22dac19b8b8a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_requests', sa.Column('booking_type', sa.Enum('single', 'range', 'subscription', name='booking_type_enum'), nullable=False, server_default='single'))
    op.add_column('booking_requests', sa.Column('date_single', sa.Date(), nullable=True))
    op.add_column('booking_requests', sa.Column('date_from', sa.Date(), nullable=True))
    op.add_column('booking_requests', sa.Column('date_to', sa.Date(), nullable=True))
    op.add_column('booking_requests', sa.Column('lessons_per_week', sa.Integer(), nullable=True))
    op.add_column('booking_requests', sa.Column('total_lessons', sa.Integer(), nullable=True))
    op.add_column('booking_requests', sa.Column('completed_lessons', sa.Integer(), nullable=True))
    op.add_column('booking_requests', sa.Column('schedule_note', sa.Text(), nullable=True))
    op.drop_column('booking_requests', 'lesson_held')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_requests', sa.Column('lesson_held', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('booking_requests', 'schedule_note')
    op.drop_column('booking_requests', 'completed_lessons')
    op.drop_column('booking_requests', 'total_lessons')
    op.drop_column('booking_requests', 'lessons_per_week')
    op.drop_column('booking_requests', 'date_to')
    op.drop_column('booking_requests', 'date_from')
    op.drop_column('booking_requests', 'date_single')
    op.drop_column('booking_requests', 'booking_type')
    # ### end Alembic commands ###
